name: Run Python script twice daily

on:
  schedule:
    # Ejecutar a las 8 AM y 8 PM todos los días
    - cron: '*/2 * * * *'  # Ejecutar cada 2 minutos
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Instalar dependencias desde requirements.txt si lo tienes..
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar tu script Python
      - name: Run Python script
        run: |
          python nombre_del_script.py
