name: Automate Data Download

on:
  schedule:
    - cron: '0 10,22,0-2 * * *'  # Ejecutar a las 7am, 7pm, 21 pm, 11pm
    - cron: '30 1 * * *'         # A las 22:30 UTC
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # Asegúrate de hacer el checkout de la rama 'main'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Cambia esto a la versión que necesitas

    - name: Install dependencies
      run: |
        pip install pandas
        pip install openpyxl
        pip install git+https://github.com/eskerda/pybikes.git
        pip install requests
        pip install scipy
        pip install pytz

    - name: Run script
      run: python automatizar_nube.py  # Asegúrate de que este es el nombre correcto de tu archivo
# Aquí agregamos los pasos para subir los cambios de vuelta al repositorio
    - name: Commit changes if the Excel file is updated
      run: |
        git config --local user.email "j.venegasgutierrez@gmail.com"
        git config --local user.name "Juan"
        git add bd_estacion.xlsx
        git commit -m "Update Excel file with new data" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main # Asegúrate de hacer push a la rama 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token secreto de GitHub para poder hacer push
