name: Download and Process Bike Data

on:
  workflow_dispatch:
  schedule:
    # Ejecutar cada 2 minutos
    - cron: "*/2 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Especifica la versión de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install openpyxl
          pip install scipy
          pip install git+https://github.com/eskerda/pybikes.git

      - name: Run Python script
        run: |
          python automatizar_nube.py  # Asegúrate de que el nombre de tu script sea correcto
