name: Automate Data Download

on:
  schedule:
    - cron: '*/2 * * * *'  # Ejecutar cada 2 minutos
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Cambia esto a la versión que necesitas

    - name: Install dependencies
      run: |
        pip install pandas
        pip install openpyxl
        pip install scipy
        pip install git+https://github.com/eskerda/pybikes.git
        pip install requests

    - name: Run script
      run: python automatizar_nube.py  # Asegúrate de que este es el nombre correcto de tu archivo
